sudo: required
language: node_js
node_js:
  - "10"
  - "8"
services:
  - docker
before_install:
  - docker-compose up -d
install:
  - yarn --ignore-engines
  - yarn build:webdriver
  - cp packages/webdriver/build/webdriver.js test/static/
  - yarn build:selianize
  - yarn build:runner
script:
  - yarn lint
  - yarn test
  - yarn test:webdriver --server http://localhost:4444/wd/hub
