sudo: required
language: node_js
cache:
  yarn: true
node_js:
  - "12"
services:
  - docker
addons:
  firefox: latest
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - sudo apt-get update
  - sudo apt-get install -y dpkg
  - sudo apt-get install -y google-chrome-stable
install:
  - yarn --ignore-engines
  - yarn build
  - yarn download-drivers
script:
  - yarn typecheck
  - yarn lint
  - yarn test
