sudo: required
language: node_js
cache:
  yarn: true
  pip: true
  directories:
    - .peru
node_js:
  - "12"
  - "10"
services:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - pyenv install -s 3.6.0
  - pyenv shell 3.6.0
  - pip3 install peru
  - peru sync
install:
  - yarn --ignore-engines
  - cd website && yarn && cd ..
  - yarn run lerna run build --ignore selenium-ide-extension --ignore selenium-ide-extension-boilerplate
  - NODE_ENV="staging" yarn build:ext
  - docker-compose up -d
script:
  - yarn lint
  - yarn test
  - yarn test:webdriver
  - yarn test:runner --server http://localhost:4444/wd/hub --force
