sudo: required
language: node_js
cache:
  yarn: true
node_js:
  - "10"
services:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --ignore-engines
  - yarn build
script:
  - yarn lint
  - yarn test
