sudo: required
language: node_js
cache:
  yarn: true
  pip: true
  directories:
    - .peru
node_js:
  - "10"
  - "8"
services:
  - docker
before_install:
  - pyenv install -s 3.6
  - pyenv shell 3.6
  - pip3 install peru
  - peru sync
install:
  - yarn --ignore-engines
  - yarn build:webdriver
  - yarn build:selianize
  - yarn build:runner
  - NODE_ENV="staging" yarn build:ext
  - docker-compose up -d
script:
  - yarn lint
  - yarn test
  - yarn test:webdriver
  - yarn test:runner --server http://localhost:4444/wd/hub
  - EXT_PATH="/ext-build" SERVER="http://localhost:4444/wd/hub" yarn test:ext
