sudo: required
language: node_js
node_js:
  - "node"
services:
  - docker
before_install:
  - docker-compose up -d
script:
  - yarn lint
  - yarn test
  - yarn build:runner
  - yarn build:selianize
  - yarn build:runner:examples
  - yarn test:webdriver --server http://localhost:4444/wd/hub
