version: '3'
services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - "./tests/static:/usr/share/nginx/html:ro"
  selenium:
    image: "selenium/standalone-chrome:3.11.0-antimony"
    ports:
      - "4444:4444"
    volumes:
      - "./packages/selenium-ide-extension/build:/ext-build"
