version: '3'
services:
  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - "./tests/static:/usr/share/nginx/html:ro"
  selenium:
    image: "selenium/standalone-chrome:3.14.0-krypton"
    ports:
      - "4444:4444"
    volumes:
      - "./packages/selenium-ide/build:/ext-build"
