version: '3'
services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - "./tests/static:/usr/share/nginx/html:ro"
  selenium:
    image: "selenium/standalone-chrome-debug:3.11.0-antimony"
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - "./packages/side-recorder/build:/recorder-ext-build"
