name: 'Release'

on:
  push:
    branches: [trunk]

jobs:
  release:
    runs-on: macos-11
    if: github.repository == 'seleniumhq/selenium-ide'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build all JS
        run: yarn build
      - name: Publish non IDE packages to npm
        run: npx lerna publish --canary --yes --no-verify-access from-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install electron-builder dependencies
        run: yarn global add dmg-license
      - name: Build selenium-ide binaries
        run: yarn build:electron
      - name: Set env from current release
        run: >
          echo "SIDE_RELEASE_VERSION=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV
        working-directory: ./packages/selenium-ide
      - name: Check env is there
        run: echo "${{ env.SIDE_RELEASE_VERSION }}"
      - name: Release latest selenium-ide on github
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Nightly (Unstable)"
          files: packages/selenium-ide/dist/Selenium*
      - name: Release selenium-ide on github
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "${{ env.SIDE_RELEASE_VERSION }}"
          prerelease: false
          files: packages/selenium-ide/dist/Selenium*
        continue-on-error: true
